### ISSUE TITLE
Fake Players don't show up

### ISSUE THREAD

**Issue by OdeuoOreo** [herby2212/FakePlayers#10]
It says: It took 0.073284722s to simulate 0 players. Even though I wrote 8 in my config.
Config: https://pastebin.com/hd27LQ8V
log: https://pastebin.com/4ytK3df0

**Comment by herby2212** [comment]
It seems the issue comes from the newest MC version (1.19.2). I will take a look into it.

**Comment by herby2212** [comment]
This ticket will be closed as further informations will be managed by ticket #11 .
