### ISSUE TITLE
When adding the plugin to the server 10 more invisible people spawn 

### ISSUE THREAD

**Issue by SuperSerferNow** [herby2212/FakePlayers#14]
The title is enough

**Comment by herby2212** [comment]
You will need to provide more informations like your console log, a detailed description and your config.

**Comment by SuperSerferNow** [comment]
I add the mod to the server and 10 random people with no name spawn. I don't know what else to say.

**Comment by herby2212** [comment]
Well you will need to configure the plugin and you should be familiar about what it does. Without a console log I can't identify the issue.

**Comment by herby2212** [comment]
Closed as no additional informations were provided.
