### ISSUE TITLE
When added to the server 10 people (fakeplayers) automatically join 

### ISSUE THREAD

**Issue by SuperSerferNow** [herby2212/FakePlayers#17]
If you have more question please respond on my discord SuperSerferNow#0236 as I don't go on github often.

**Comment by Stage4000** [comment]
You have already opened this issue, it has been responded to appropriately and closed. If you can't figure out something this simple, you should probably give up on running a server. 

Edit the config.

**Comment by SuperSerferNow** [comment]
> You have already opened this issue, it has been responded to appropriately and closed. If you can't figure out something this simple, you should probably give up on running a server.
> 
> Edit the config.

ok ty  : DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
