### ISSUE TITLE
Add auto complete for commands

### ISSUE THREAD

**Issue by Josh65-2201** [herby2212/FakePlayers#18]
Currently running an in game commands just show `/fakeplayer` in chat which makes no sense. Removing that when entering a command and adding auto complete for them would be much more helpful.

**Comment by herby2212** [comment]
Good suggestion. I will put it on the list for the next release.

**Comment by herby2212** [comment]
Implemented with the newest release of the 2.8-SNAPSHOT and commit (https://github.com/herby2212/FakePlayers/commit/f2e851ac96f95189cca0a237e5352ea6221494a6).
