### ISSUE TITLE
Update to 1.19.4?

### ISSUE THREAD

**Issue by marlester-dev** [herby2212/FakePlayers#24]
Simply not working on 1.19,4

**Comment by marlester-dev** [comment]
/fakeplayers create fakeplayer not working
advanced fakeplayers not working

**Comment by marlester-dev** [comment]
@herby2212

**Comment by herby2212** [comment]
Greetings,
a update will be released in the coming week.

**Comment by marlester-dev** [comment]
👍, waiting for an update

**Comment by herby2212** [comment]
Fixed with the updated release of the 2.8-SNAPSHOT and commit (https://github.com/herby2212/FakePlayers/commit/b78b36a6a816311fe0b5d8f68774a81a85595cc7).
