### ISSUE TITLE
Server 24/7

### ISSUE THREAD

**Issue by BobtheBob123456** [herby2212/FakePlayers#9]
Question, does this plugin keep the server running if there are fake players enabled 24/7?

**Comment by herby2212** [comment]
Are you using a plugin that is shutting the server off when no players are online? I will need more informations to help you.

**Comment by BobtheBob123456** [comment]
No I am using a server hosting site that turns off my server if no one is online. I thought that maybe if I had a fake player plugin installed on the server would think a player was online and stay on for 24/7

**Comment by herby2212** [comment]
Depends on how the server is counting the online players so it could happen. 
You can try it out and if it stays online I can publish a update to fix it.

**Comment by BobtheBob123456** [comment]
No, I want my server to be on 24/7 so I don't have to start it every time someone wants to join.

**Comment by herby2212** [comment]
Well again please try it out. It may work for you then exactly like you need it.
